import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  background: {
    flex: 1,
    backgroundColor: 'white',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    marginTop: -35,
    zIndex: 11,
  },
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  mainContent: {
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  loadingComponent: {
    paddingVertical: 50,
    alignItems: 'center',
  },
  exzoLogo: {
    width: 100,
    height: 100,
  },
  swapCard: {
    backgroundColor: 'white',
    borderRadius: 6,
    paddingBottom: 15,
    shadowColor: '#3F77AC',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.1,
    shadowRadius: 50,
    elevation: 3,
  },
  swapHeader: {
    borderBottomWidth: 1,
    borderColor: 'rgba(108, 117, 125, 0.1)',
    paddingHorizontal: 20,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  swapHeaderButtons: {
    flexDirection: 'row',
  },
  swapHeaderButtonText: {
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 24,
    color: '#8FA2B7',
    width: 70,
    marginRight: 5,
  },
  swapHeaderButtonTextActive: {
    color: '#3755F0',
  },
  swapForm: {
    marginTop: 20,
    paddingHorizontal: 20,
  },
  swapText: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '400',
    color: '#34384C',
    marginBottom: 10,
  },
  swapTokenWrapper: {},
  swapToken: {
    backgroundColor: '#FCFCFE',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 100,
    padding: 8,
    borderWidth: 1,
    borderColor: '#F0F3FF',
    minWidth: 120,
  },
  tokenMax: {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '400',
    color: '#3755F0',
  },
  tokenLogo: {
    width: 25,
    height: 25,
    marginRight: 10,
  },
  tokenSymbol: {
    fontSize: 16,
    fontWeight: '400',
    marginRight: 5,
  },
  amount: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F0F3FF',
    paddingVertical: 11,
    paddingHorizontal: 15,
    marginRight: 10,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#F0F3FF',
  },
  amountInput: {
    flex: 1,
    fontWeight: '500',
    fontSize: 16,
    padding: 0,
    marginRight: 10,
    textAlign: 'left',
  },
  amountText: {
    fontWeight: '500',
    fontSize: 16,
    textAlign: 'left',
  },
  swapIcon: {
    transform: [{ rotate: '90deg' }],
  },
  tokenBalance: {
    fontSize: 12,
    fontWeight: '400',
    color: '#8FA2B7',
  },
  tokenError: {
    height: 15,
  },
  tokenErrorText: {
    position: 'absolute',
    top: 0,
    left: 0,
    color: 'red',
    marginTop: 5,
    fontSize: 12,
    fontWeight: '400',
  },
  slippageValue: {
    marginTop: 5,
    fontSize: 12,
    fontWeight: '500',
    alignSelf: 'flex-end',
  },
  swapButton: {
    marginTop: 20,
    backgroundColor: '#3755F0',
    paddingVertical: 12,
    borderRadius: 100,
  },
  buttonText: {
    textAlign: 'center',
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '700',
    color: 'white',
  },
  transactionDetails: {
    marginTop: 30,
    paddingHorizontal: 5,
  },
  textWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 5,
  },
  detailText: {
    fontSize: 14,
    fontWeight: '500',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalHeader: {
    backgroundColor: 'white',
    borderBottomWidth: 1,
    borderColor: 'gray',
    paddingBottom: 10,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '700',
  },
  closeButton: {
    backgroundColor: 'white',
    padding: 2,
    borderRadius: 10,
  },
  modalBody: {
    width: '80%',
    height: '60%',
    backgroundColor: 'white',
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 15,
  },
  modalTokenItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
  },
  SlippageInput: {
    borderColor: '#D1DFEE',
    borderWidth: 1,
    padding: 0,
    paddingHorizontal: 10
  },
  slippageWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 5,
    marginTop: 10,
    marginBottom: 20,
  },
  slippageButton: {
    margin: 2,
    paddingVertical: 7,
    paddingHorizontal: 10,
    alignSelf: 'flex-start',
    borderRadius: 10,
  },
  selected: {
    borderWidth: 0.5,
    borderColor: 'blue',
    backgroundColor: 'white',
  },
  slippageButtonText: {
    fontSize: 14,
    color: 'black',
  },
  settingsModalContainer: {
    flex: 1,
    backgroundColor: 'white',
  },
  settingsModalBody: {
    flex: 1,
    paddingTop: 30,
    paddingBottom: Platform.OS === 'ios' ? 40 : 30,
    paddingHorizontal: 20,
  },
  settingsModalHeader: {
    marginTop: Platform.OS === 'ios' ? 60 : 40,
    paddingHorizontal: 20,
  },
  settingsModalTitle: {
    fontSize: 24,
    color: '#121212',
    fontWeight: '500',
    marginTop: 25,
  },
  settingsModalText: {
    fontSize: 12,
    fontWeight: '400',
    color: '#8FA2B7',
    marginBottom: 10,
  },
  settingsModalTextBold: {
    fontSize: 14,
    fontWeight: '500',
    marginRight: 10
  },
  settingsExchages: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: '13',
    backgroundColor: '#F0F3FF',
    borderRadius: 4,
    paddingVertical: 13,
    paddingHorizontal: 20,
  },
  settingsExchagesText: {
    fontSize: 12,
    color: '#011B21',
    marginRight: 'auto',
  },
  settingsGas: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  settingsGasItem: {
    width: 100,
    height: 110,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#D1DFEE',
    borderRadius: 4,
  },
  settingsGasItemActive: {
    borderColor: '#3755F0',
  },
  settingsGasItemTilte: {
    fontSize: 14,
    fontWeight: '500',
    color: '#011B21',
  },
  settingsGasItemText: {
    fontSize: 12,
    fontWeight: '400',
    color: '#8FA2B7',
    marginTop: 5,
  },
  settingsGasInput: {
    paddingVertical: 7,
    paddingHorizontal: 0,
    width: 42,
    backgroundColor: '#F0F3FF',
    textAlign: 'center',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#3755F0',
    marginRight: 5,
  },
  settingsGasItemRadio: {
    width: 16,
    height: 16,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: '#D1DFEE',
    position: 'absolute',
    top: 10,
    left: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsGasItemRadioActive: {
    borderColor: '#3755F0',
  },
  settingsGasRadioInner: {
    backgroundColor: '#3755F0',
    borderWidth: 1,
    borderColor: '#D1DFEE',
    width: 8,
    height: 8,
    borderRadius: 100,
  },
});
