import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  background: {
    flex: 1,
    backgroundColor: 'white',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    marginTop: -35,
    zIndex: 11,
  },
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  mainContent: {
    flex: 1,
    borderTopRightRadius: 32,
    borderTopLeftRadius: 32,
    paddingVertical: 30,
  },
  swipeList: {
    paddingHorizontal: 20,
  },
  title: {
    fontWeight: '500',
    fontSize: 18,
    lineHeight: 24,
    color: '#2C3E50',
    paddingHorizontal: 20,
  },
  wallets: { marginTop: 15, marginBottom: 20 },
  wallet: {
    marginVertical: 10,
    backgroundColor: 'white',
    borderRadius: 8,
    paddingTop: 15,
    paddingBottom: 20,
    paddingLeft: 15,
    paddingRight: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'white',
    shadowColor: '#F1F4F6',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 1,
    shadowRadius: 25,
    elevation: 3,
  },
  logo: {
    backgroundColor: '#013BFF',
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 100,
    marginRight: 20,
  },
  walletTitle: {
    fontSize: 16,
    lineHeight: 19,
    fontWeight: '500',
    marginBottom: 5,
  },
  walletBalance: {
    fontSize: 12,
    lineHeight: 14,
    color: '#AFB6D0',
    fontWeight: '400',
  },
  border: {
    width: 24,
    height: 24,
    borderWidth: 1.5,
    borderColor: '#AFB6D0',
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fill: {
    width: 14,
    height: 14,
    backgroundColor: '#013BFF',
    borderRadius: 100,
  },
  deleteButtonWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    justifyContent: 'flex-end',
    paddingRight: 10,
  },
  deleteButton: {
    backgroundColor: 'red',
    padding: 5,
    borderRadius: 5,
  },
  editButton: {
    backgroundColor: 'green',
    padding: 5,
    borderRadius: 5,
    marginHorizontal: 10,
  },
  deleteButtonText: {
    color: 'white',
    fontWeight: '500',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  formLayout: {
    padding: 10,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  nameInput: {
    width: 250,
    padding: 5,
    backgroundColor: '#dddddd',
    color: 'black',
    borderRadius: 5,
  },
  buttonGroup: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cancelButton: {
    padding: 7,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#013BFF',
  },
  updateButton: {
    padding: 7,
    backgroundColor: '#013BFF',
    borderRadius: 5,
  },
  buttonText: {
    color: 'white',
    fontWeight: '500',
  },
});
