export const ApplicationProperties = {
  BACKEND_API_URL: 'http://localhost:4000/',
  // BACKEND_API_URL: 'http://18.218.253.7/api/',
  ETHERSCAN_API_KEY: 'ZRHADFZI286DYZUC6JV3ASSSCQ2FGZMT3I',
  ETHERSCAN_API_URL: 'https://etherscan.io/',
  CRYPTOCOMPARE_API_KEY: 'dab9c63af8475f6cfec34b7d8f653ff96636faee5178a7e66a5ee01d8e3a4579',
  COINMARKETCAP_API_URL: 'https://pro-api.coinmarketcap.com/v1/',
  COINMARKETCAP_API_KEY: 'ea47645d-15c4-4737-b54c-371adbdc19f4',
  CRYPTONEWS_API_KEY: 'mdh341olew6d06m96lvmqtxjf83fjmunnj0ddj0d',
  ONEINCH_API_URL: 'https://api.1inch.exchange/v3.0',
  COINGECKO_API_URL: 'https://api.coingecko.com/api/v3/',
  DEFAULT_CURRENCY: { key: 'USD', symbol: '$', value: 0 },
  WALLET_COIN_TYPES: [
    'bitcoin',
    'ethereum',
    'smartchain',
    // 'bitcoincash',
    // 'doge',
    // 'polygon',
    // 'solana',
    // 'smartchain',
    // 'tron',
  ],
  API_PROVIDERS: {
    etherscan: this.ETHERSCAN_API_KEY,
    infura: {
      projectId: '997c4a18ee624b0a9408733249fc4a9a',
      projectSecret: 'df04172bda054bdf9848d58b80d0080a',
    },
    alchemy: 'dDowuL9P6nWr22cur5nv6ww_Oj23Jteu',
  },
  Oxapi: {
    1: 'https://api.0x.org/',
    56: 'https://bsc.api.0x.org/',
    3: 'https://ropsten.api.0x.org/',
    137: 'https://polygon.api.0x.org/',
    43113: 'https://avalanche.api.0x.org/',
  },
  MainABI: [
    {
      constant: true,
      inputs: [{ name: '_owner', type: 'address' }],
      name: 'balanceOf',
      outputs: [{ name: 'balance', type: 'uint256' }],
      type: 'function',
    },
    {
      constant: true,
      name: 'decimals',
      outputs: [{ name: 'decimals', type: 'uint8' }],
      type: 'function',
    },
    {
      constant: true,
      name: 'symbol',
      outputs: [
        {
          internalType: 'string',
          name: '',
          type: 'string',
        },
      ],
      type: 'function',
    },
  ],
  transactionABI: [
    {
      constant: false,
      inputs: [
        {
          name: '_to',
          type: 'address',
        },
        {
          name: '_value',
          type: 'uint256',
        },
      ],
      name: 'transfer',
      outputs: [
        {
          name: 'success',
          type: 'bool',
        },
      ],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: false,
      inputs: [
        {
          name: '_spender',
          type: 'address',
        },
        {
          name: '_value',
          type: 'uint256',
        },
      ],
      name: 'approve',
      outputs: [
        {
          name: 'success',
          type: 'bool',
        },
      ],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      constant: true,
      inputs: [
        {
          name: '',
          type: 'address',
        },
        {
          name: '',
          type: 'address',
        },
      ],
      name: 'allowance',
      outputs: [
        {
          name: '',
          type: 'uint256',
        },
      ],
      payable: false,
      stateMutability: 'view',
      type: 'function',
    },
  ],
  ACTIVE_NETWORK: {
    name: 'homestead',
    chainId: 1,
    ensAddress: '',
    apiUrl: 'https://api.etherscan.io/',
    txUrl: 'https://etherscan.io/tx/',
    displayName: 'Ethereum Mainnet',
    readonly: true,
    symbol: 'ETH',
  },
  NETWORKS: [
    {
      name: 'https://bsc-dataseed.binance.org/',
      chainId: 56,
      ensAddress: '',
      apiUrl: 'https://bscscan.com',
      txUrl: 'https://bsc-dataseed.binance.org/',
      displayName: 'Binance Smart Chain',
      readonly: true,
      symbol: 'BNB',
    },
    {
      name: 'homestead',
      chainId: 1,
      ensAddress: '',
      apiUrl: 'https://api.etherscan.io/',
      txUrl: 'https://etherscan.io/tx/',
      displayName: 'Ethereum Mainnet',
      readonly: true,
      symbol: 'ETH',
    },
    // {
    //   name: 'https://data-seed-prebsc-1-s1.binance.org:8545/',
    //   chainId: 97,
    //   ensAddress: '',
    //   apiUrl: 'https://api-testnet.bscscan.com/',
    //   displayName: 'Smart Chain - Testnet',
    //   readonly: true,
    //   symbol: 'BNB',
    // },
    // {
    //   name: 'rinkeby',
    //   chainId: 4,
    //   ensAddress: '',
    //   apiUrl: 'https://api-rinkeby.etherscan.io/',
    //   txUrl: 'https://rinkeby.etherscan.io/tx/',
    //   displayName: 'Rinkeby Test Network',
    //   readonly: true,
    //   symbol: 'ETH',
    // },
    // {
    //   name: 'kovan',
    //   chainId: 42,
    //   ensAddress: '',
    //   apiUrl: 'https://api-kovan.etherscan.io/',
    //   txUrl: 'https://kovan.etherscan.io/tx/',
    //   displayName: 'Kovan Test Network',
    //   readonly: true,
    //   symbol: 'ETH',
    // },
    // {
    //   name: 'ropsten',
    //   chainId: 3,
    //   ensAddress: '',
    //   apiUrl: 'https://api-ropsten.etherscan.io/',
    //   txUrl: 'https://ropsten.etherscan.io/tx/',
    //   displayName: 'Rosten Test Network',
    //   readonly: true,
    //   symbol: 'ETH',
    // },
    // {
    //   name: 'goerli',
    //   chainId: 5,
    //   ensAddress: '',
    //   apiUrl: 'https://api-goerli.etherscan.io/',
    //   txUrl: 'https://goerli.etherscan.io/tx/',
    //   displayName: 'Goerli Testnet',
    //   readonly: true,
    //   symbol: 'ETH',
    // },
  ],
  COMMON_TOKENS: [
    {
      name: 'Bitcoin',
      symbol: 'BTC',
      decimals: 18,
      address: '',
      slug: 'bitcoin',
    },
    {
      name: 'Ethereum',
      symbol: 'ETH',
      decimals: 18,
      address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
      slug: 'ethereum',
    },
    {
      name: 'Binance Coin',
      symbol: 'BNB',
      decimals: 18,
      address: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
      slug: 'binance-coin',
    },
    {
      name: 'Solana',
      symbol: 'SOL',
      decimals: 9,
      address: '',
      slug: 'solana',
    },
    {
      name: 'Cardano',
      symbol: 'ADA',
      decimals: 18,
      address: '0x3ee2200efb3400fabb9aacf31297cbdd1d435d47',
      slug: 'cardano',
    },
    {
      name: 'Dogecoin',
      symbol: 'DOGE',
      decimals: 8,
      address: '0xba2ae424d960c26247dd6c32edc70b295c744c43',
      slug: 'dogecoin',
    },
    {
      name: 'SHIBA INU',
      symbol: 'SHIB',
      decimals: 18,
      address: '0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce',
      slug: 'shiba-inu',
    },
  ],
  MAIN_TOKEN: {
    name: 'ExzoCoin',
    symbol: 'EXZO',
    decimals: 9,
    address: '0xF8fC63200e181439823251020d691312FDcF5090',
  },
};
